#building phonebook application using nodejs. 
version: '3.5'

services:
  phonebook:
    build: . # build from docker file
    command: ["npm", "start" ]
    ports: 
      - 3000:3000 
    volumes:
      - ./:/usr/src/app 
      - node_modules:/usr/src/app/node_modules   
volumes:
  node_modules: